name: Release Elastic Beanstalk

on:
  push:
    branches: [ci/add-deploy-ebs]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: kraicklist-isdzulqor
          environment_name: kraicklistisdzulqor-env
          version_label: kraicklist-isdzulqor-1
          region: us-east-2
          deployment_package: deploy.zip