name: Release Elastic Beanstalk

on:
  push:
    branches: [ci/add-deploy-ebs]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      APP_VERSION: ${GITHUB_SHA::8}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set outputs
        id: vars
        run: | 
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Set up Go 1.15.2
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2
        id: go
      - name: Build kraicklist app
        run: GOOS=linux GOARCH=amd64 go build -o bin/application main.go
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: kraicklist-isdzulqor
          environment_name: kraicklistisdzulqor-env
          version_label: ${{ steps.vars.outputs.sha_short }}
          region: us-east-2
          deployment_package: deploy.zip