name: Release AWS

on:
  push:
    branches: [ci/add-deploy-ec2]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      APP_VERSION: ${GITHUB_SHA::8}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set outputs
        id: vars
        run: | 
          # get tag name
          tag_name="${GITHUB_REF#refs/tags/}"
          echo ::set-output name=tag_name::$tag_name
      - name: Set up Go 1.15.2
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2
        id: go
      - name: Build kraicklist app
        run: GOOS=linux GOARCH=amd64 go build -o bin/application main.go
      
      # Deployment to Elastic Beanstalk
      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'
      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v16
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     application_name: kraicklist-isdzulqor
      #     environment_name: kraicklistisdzulqor-env
      #     version_label: ${{ steps.vars.outputs.tag_name }}
      #     region: us-east-2
      #     deployment_package: deploy.zip
      
      # Deployment to EC2
      - name: ssh deploy to AWS EC2
        uses: easingthemes/ssh-deploy@v2.1.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_AWS_EC2_PRIVATE_KEY }}
          SOURCE: "./bin"
          REMOTE_HOST: "3.141.106.12"
          REMOTE_USER: "isdzulqor"
          TARGET: "~"

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: "3.141.106.12"
          username: "isdzulqor"
          key: ${{ secrets.SSH_AWS_EC2_PRIVATE_KEY }}
          port: 22
          script: whoami