name: testing_multiple_2

on:
  pull_request:
    paths-ignore:
      - "static/**"
    branches: [master]
  push:
    paths-ignore:
      - "static/**"
    branches: [master]

jobs:
  testing_multiple_2:
    name: testing_multiple_2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Go 1.15.2
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2
        id: go
      - name: Build kraicklist app
        run: go build main.go
      - name: Sleep 3 minutes
        run: |
          sleep 180