name: Test Integration

on:
  pull_request:
    paths-ignore:
      - "static/**"
  push:
    paths-ignore:
      - "static/**"
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Stack
        run: docker-compose -f docker-compose.test.yaml up -d
      - name: Set up Go 1.15.2
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2
      - name: Check Kraicklist Readiness
        timeout-minutes: 3
        run: |
          response=`curl --fail localhost:7777/health --header 'x-health-token: health-token' --silent || echo failed`
          while [[ "$response" == failed ]] ; do
            echo "Sleep 5 seconds. retrying..."
            sleep 5
            response=`curl --fail localhost:7777/health --header 'x-health-token: health-token' --silent || echo failed`
          done
          echo $response
      - name: Test
        env:
          PORT: 7777
        run: go test -v ./...